In [1]:
from makerlib import wind_direction_df

In [2]:
%%time
wind_direction_df(vwnd_file='data/example_vwind.nc', uwnd_file='data/example_uwind.nc', 
                  startdate='2017-01-20', enddate='2017-02-01', 
                  level=300, lon=220, lat=40, s=False, ret=True)

CPU times: user 104 ms, sys: 13.5 ms, total: 117 ms
Wall time: 123 ms

,mean v-wind (m/s),mean u-wind (m/s),wind direction from (deg),wind direction to (deg),cardinal direction,wind speed in direction
2017-01-20,-21.275000,86.649994,283.794836,103.794836,WNW,89.223579
2017-01-21,9.750000,65.875000,261.580912,81.580912,W,66.592628
2017-01-22,-13.050000,21.099998,301.736106,121.736106,WNW,24.809523
2017-01-23,-41.349998,23.050001,330.863106,150.863106,NNW,47.340521
2017-01-24,9.850000,23.700001,247.431652,67.431652,WSW,25.665396
2017-01-25,-7.025000,27.625000,284.267813,104.267813,WNW,28.504232
2017-01-26,10.300000,30.824999,251.523239,71.523239,WSW,32.500316
2017-01-27,27.824999,30.874998,227.974363,47.974363,SW,41.563158
2017-01-28,48.200001,35.774998,216.583538,36.583538,SW,60.025749
2017-01-29,39.650002,24.424999,211.633696,31.633696,SSW,46.569338
2017-01-30,37.325001,0.300000,180.460506,0.460506,S,37.326206
2017-01-31,26.850002,-12.099999,155.741210,-24.258790,SSE,29.450511
2017-02-01,6.475000,-6.400001,135.333757,-44.666243,SE,9.104155

In [3]:
import iris 
from subset import subset_nc

iris.FUTURE.cell_datetime_objects = False

subset_cube = subset_nc(filename='data/example_vwind.nc', startdate='2017-01-20', enddate='2017-02-01', 
                        level=300, lat_min=40, lat_max=60, lon_min=180, lon_max=200)

iris.io.save(subset_cube,'data/example_subset.nc')

In [4]:
import iris.pandas as ip 
df = ip.as_data_frame(subset_cube[0], copy=True) #index 0 is startdate
df

,180.0,182.5,185.0,187.5,190.0,192.5,195.0,197.5,200.0
60.0,-8.200000,-7.325000,-6.225000,-4.825000,-2.800000,0.225000,4.475000,9.625000,14.750000
57.5,-9.775000,-9.000000,-7.675000,-5.900000,-3.275000,0.500000,5.675000,11.825000,18.100000
55.0,-11.624999,-11.075001,-9.474999,-7.000000,-3.700000,0.600000,5.925000,11.999999,18.074999
52.5,-12.475000,-12.525001,-10.900000,-7.925000,-3.925000,0.625000,5.475000,10.300000,14.750000
50.0,-11.850000,-12.775001,-11.500000,-8.475000,-4.350000,-0.025000,3.925000,7.150000,9.450000
47.5,-11.425000,-12.925000,-12.025000,-9.225000,-5.300000,-1.325000,2.050000,4.400000,5.575000
45.0,-13.575000,-14.975000,-13.700001,-10.375000,-6.025000,-1.550000,2.250000,5.150001,6.775000
42.5,-18.225000,-18.525002,-15.650000,-10.549999,-4.350000,1.750000,7.150000,11.300000,13.825001
40.0,-21.099998,-19.449999,-14.350000,-6.800000,1.775002,9.724998,16.174999,20.600000,22.650000